{
 "title": "Docker Registry",
 "tags": [
  "docker",
  "registry",
  "internals"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "query_result(registry_http_in_flight_requests)"
   },
   {
    "name": "app",
    "query": "query_result(registry_http_in_flight_requests{kubernetes_namespace=\"$namespace\"})"
   },
   {
    "name": "instance",
    "query": "query_result(up{app=\"$app\"})"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time",
   "type": "singlestat",
   "description": "start time of the process",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_start_time_seconds{app=\"$app\", instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "Total Cache Requests",
   "type": "singlestat",
   "description": "The number of cache request received",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "registry_storage_cache_total{instance=\"$instance\",type=\"Request\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Total Hit Cache Requests",
   "type": "singlestat",
   "description": "The number of cache request received (hits)",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "registry_storage_cache_total{instance=\"$instance\",type=\"Hit\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Total Missed Cache Requests",
   "type": "singlestat",
   "description": "The number of cache request received (miss)",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "registry_storage_cache_total{instance=\"$instance\",type=\"Miss\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Virtual Memory Usage",
   "type": "singlestat",
   "description": "Process Virtual Memory Usage",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{app=\"$app\", instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "The HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(rate(registry_http_requests_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "In-Flight HTTP Requests",
   "type": "graph",
   "description": "The in-flight HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "registry_http_in_flight_requests{instance=\"$instance\"}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Registry Cache Requests Rate",
   "type": "graph",
   "description": "The rate of registry cache requests",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(rate(registry_storage_cache_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Upload HTTP Request Latencies in seconds (blob_upload)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob_upload\"}[10m])"
    }
   ]
  }
 ]
}